[package]
name = "rust-2"
version = "0.1.0"
edition = "2018"

[dependencies]
rustyline = "9.1.2"
regex = "1.5.5"
lazy_static = "1.4.0"

[[bin]]
name = "step0_repl"
path = "step0_repl.rs"

[[bin]]
name = "step1_read_print"
path = "step1_read_print.rs"
